Update AnalysisDomain.h
Forward declaration causes problems when building with Bazel

ERROR: third_party/crosstool/v18/stable/toolchain/include/c++/v1/type_traits:1701:59 incomplete type 'psr::LLVMBasedICFG' used in type trait expression
    : public integral_constant<bool, __is_base_of(_Bp, _Dp)> {};
                                                          ^
third_party/crosstool/v18/stable/toolchain/include/c++/v1/type_traits:1706:7 in instantiation of template class 'std::is_base_of<psr::ICFG<const llvm::Instruction *, const llvm::Function *>, psr::LLVMBasedICFG>' requested here
    = is_base_of<_Bp, _Dp>::value;
      ^
third_party/phasar/include/phasar/PhasarLLVM/DataFlowSolver/Mono/InterMonoProblem.h:45:22 in instantiation of variable template specialization 'std::is_base_of_v<psr::ICFG<const llvm::Instruction *, const llvm::Function *>, psr::LLVMBasedICFG>' requested here
  static_assert(std::is_base_of_v<ICFG<n_t, f_t>, i_t>,
                     ^
third_party/phasar/include/phasar/PhasarLLVM/DataFlowSolver/Mono/Problems/InterMonoFullConstantPropagation.h:40:14 in instantiation of template class 'psr::InterMonoProblem<psr::IntraMonoFullConstantPropagationAnalysisDomain>' requested here
      public InterMonoProblem<IntraMonoFullConstantPropagationAnalysisDomain> {
             ^
third_party/phasar/include/phasar/PhasarLLVM/Domain/AnalysisDomain.h:20:7 forward declaration of 'psr::LLVMBasedICFG'
class LLVMBasedICFG;